In [1]:
import symbol as s
import pandas as pd
import numpy as np
import os
from datetime import datetime
import seaborn as sns
sns.set_style("whitegrid")

%matplotlib inline

In [3]:
symbol = s.Symbol()

In [5]:
ret = symbol.get_symbol_returns()

In [ ]:
ncount = symbol.symbol_returns_null_count()

In [ ]:
def consecutive_nulls(series):
    symbol = series.name
    series.name = 'symbol'
    null_series = pd.DataFrame(series)
    null_series['null_count'] = 0
    some series = 0 if x.isnull() else 
    return null_count
%timeit returns_null_count = ret.apply(consecutive_nulls)

In [ ]:
ncount

In [ ]:
%timeit s.null_count(ret)

In [ ]:
ret.columns[s.null_count(ret) <= 0]

In [ ]:
sma = {
    'metals_and_mining':'metals',
    'technology': 'it',
    'consumer_goods': 'fmcg',
    'pharma_and_healthcare':'pharma',
    'chemicals_and_fertilizers': 'chem', 
    'oil_and_gas':'energy',
    'industrial_equipment':'industrial_goods',
    'cement':'cement',
    'engineering_and_capital_goods':'engineering',
    'trading_and_exports':'trade', 
    'power':'energy', 
    'travel_and_hotels':'tourism', 
    'telecom':'telecom',
    'construction':'construction', 
    'industrial_cables': 'industrial_goods', 
    'banking_and_finance': 'bfsi',
    'agriculture_and_food_processing': 'agri', 
    'auto': 'auto', 
    'packaging':'misc',
    'miscellaneous':'misc', 
    'education':'edu', 
    'plastics':'misc', 
    'media':'media',
    'consumer_durables':'fmcg', 
    'sugar':'sugar', 
    'paper_and_stationery':'paper'
}

In [ ]:
pd.Series(sma).to_dict()

In [ ]:
s.clean_file('constants.h5')

In [ ]:
smeta = symbol.get_symbol_meta()
smeta.industry.replace(pd.Series(sma).to_dict())

In [2]:
s.get_store_keys('index_data.h5')

['/index_data_daily', '/index_returns_daily']

In [6]:
idata = pd.read_hdf('index_data.h5', 'index_data_daily')

In [8]:
idata.to_hdf('index_data.h5', 'index_data_daily')

In [7]:
idata

,nifty_50,nifty_next_50,nifty_midcap_50,nifty_midcap_150,nifty_smallcap_250,nifty_500,nifty_alpha_50,nifty_high_beta_50,nifty_div_opps_50,nifty_low_volatility_50,...,nifty_psu_bank,nifty_pharma,nifty_realty,nifty_pse,nifty_mnc,nifty_infra,nifty_consumption,nifty_energy,nifty_cpse,nifty_commodities
1995-01-02,1182.14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1000.00,1000.00,NaN,NaN,NaN,NaN,NaN
1995-01-03,1176.82,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1170.35,1039.85,NaN,NaN,NaN,NaN,NaN
1995-01-04,1163.72,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1162.69,1032.96,NaN,NaN,NaN,NaN,NaN
1995-01-05,1150.02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1142.31,1026.05,NaN,NaN,NaN,NaN,NaN
1995-01-06,1130.36,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1150.53,1011.17,NaN,NaN,NaN,NaN,NaN
1995-01-09,1112.10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1109.86,1001.17,NaN,NaN,NaN,NaN,NaN
1995-01-10,1079.20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1099.51,982.12,NaN,NaN,NaN,NaN,NaN
1995-01-11,1067.58,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1099.73,982.12,NaN,NaN,NaN,NaN,NaN
1995-01-12,1066.19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1101.39,984.33,NaN,NaN,NaN,NaN,NaN
1995-01-13,1074.43,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1088.60,984.33,NaN,NaN,NaN,NaN,NaN
1995-01-16,1087.80,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1088.25,1001.57,NaN,NaN,NaN,NaN,NaN
1995-01-17,1084.08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1097.63,1011.83,NaN,NaN,NaN,NaN,NaN
1995-01-18,1091.21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1084.21,1015.05,NaN,NaN,NaN,NaN,NaN
1995-01-19,1091.57,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1086.03,1019.87,NaN,NaN,NaN,NaN,NaN
1995-01-20,1075.59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1085.49,1018.34,NaN,NaN,NaN,NaN,NaN
1995-01-23,1041.78,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1061.14,996.46,NaN,NaN,NaN,NaN,NaN
1995-01-24,1019.20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1036.16,980.93,NaN,NaN,NaN,NaN,NaN
1995-01-25,1030.01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1009.06,986.37,NaN,NaN,NaN,NaN,NaN
1995-01-27,1043.59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,989.18,997.24,NaN,NaN,NaN,NaN,NaN
1995-01-30,1058.60,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,996.84,1019.51,NaN,NaN,NaN,NaN,NaN
1995-01-31,1071.23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,983.77,1032.36,NaN,NaN,NaN,NaN,NaN
1995-02-01,1061.76,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,991.91,1041.96,NaN,NaN,NaN,NaN,NaN
1995-02-02,1066.09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,989.83,1047.55,NaN,NaN,NaN,NaN,NaN
1995-02-03,1076.29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,975.95,1054.81,NaN,NaN,NaN,NaN,NaN
1995-02-06,1061.72,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,978.67,1047.74,NaN,NaN,NaN,NaN,NaN
1995-02-07,1052.76,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,965.54,1038.15,NaN,NaN,NaN,NaN,NaN
1995-02-08,1042.46,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,962.88,1032.27,NaN,NaN,NaN,NaN,NaN
1995-02-09,1045.22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,951.04,1021.25,NaN,NaN,NaN,NaN,NaN
1995-02-10,1037.16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,946.48,1016.14,NaN,NaN,NaN,NaN,NaN
1995-02-13,1029.89,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,955.00,1010.93,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2016-11-04,8433.75,22621.55,3889.60,5064.74,4931.03,7274.10,9383.46,1580.43,2097.75,8134.41,...,2961.20,10606.00,195.40,3606.45,10262.70,2774.40,3795.95,9711.15,2295.05,3062.80
2016-11-07,8497.05,22776.55,3931.75,5102.28,4998.12,7330.95,9516.35,1612.27,2117.00,8167.88,...,3075.65,10818.75,198.60,3645.45,10240.50,2774.40,3809.75,9762.05,2312.75,3095.85
2016-11-08,8543.55,22856.30,3946.85,5125.89,5002.52,7366.05,9566.15,1618.96,2125.40,8191.38,...,3073.30,10665.80,198.20,3672.10,10271.65,2779.30,3817.75,9821.70,2331.15,3112.95
2016-11-09,8432.00,22430.80,3855.30,5007.44,4867.43,7247.45,9284.06,1557.30,2084.10,8047.57,...,3137.90,10871.10,175.20,3667.35,9990.55,2745.60,3720.10,9825.45,2331.70,3064.30
2016-11-10,8525.75,22791.85,3960.25,5095.32,4953.71,7342.30,9452.94,1628.34,2113.95,8103.77,...,3411.65,10990.55,177.35,3764.25,9972.70,2816.85,3706.65,9975.50,2397.00,3149.60
2016-11-11,8296.30,22033.45,3790.55,4917.96,4778.87,7126.50,8999.57,1571.94,2055.90,7864.49,...,3320.25,10901.25,168.35,3673.10,9722.35,2741.75,3556.40,9807.45,2344.55,3069.70
2016-11-15,8108.45,21066.65,3643.40,4724.71,4540.62,6916.45,8433.32,1510.97,2011.40,7639.87,...,3395.35,10747.90,159.70,3604.45,9358.20,2700.45,3440.75,9658.30,2283.95,2945.75
2016-11-16,8111.60,21229.00,3647.75,4733.55,4553.34,6928.10,8451.72,1495.94,2017.75,7656.64,...,3372.80,10559.25,158.10,3596.95,9387.45,2711.25,3478.30,9657.80,2277.50,2936.75
2016-11-17,8079.95,21231.55,3641.40,4714.17,4524.98,6903.45,8455.21,1498.42,2010.35,7614.18,...,3377.10,10595.65,160.10,3622.50,9345.90,2702.75,3442.35,9678.40,2284.65,2933.45
2016-11-18,8074.10,21332.05,3650.25,4724.26,4547.20,6908.50,8460.02,1505.05,2016.50,7658.81,...,3382.60,10751.45,162.30,3664.65,9305.95,2718.20,3442.15,9797.25,2300.80,2956.00
2016-11-21,7929.10,20791.80,3522.25,4597.94,4383.50,6761.55,8145.92,1437.19,1982.60,7516.60,...,3149.50,10642.10,153.85,3573.70,9078.10,2661.30,3381.95,9689.60,2255.15,2894.85
2016-11-22,8002.30,21121.55,3571.25,4669.06,4422.38,6835.30,8335.47,1455.85,2009.35,7594.51,...,3154.35,10693.85,158.45,3598.35,9270.90,2653.30,3440.35,9749.30,2279.05,2942.65
2016-11-23,8033.30,21417.65,3604.60,4715.91,4502.40,6882.65,8559.00,1484.57,2029.25,7639.13,...,3162.85,10934.20,163.10,3617.85,9363.10,2680.30,3457.20,9817.00,2288.35,2982.05
2016-11-24,7965.50,21404.50,3565.60,4686.40,4503.01,6837.50,8512.21,1476.12,2034.50,7619.81,...,3201.65,10762.45,160.95,3612.35,9330.55,2671.30,3434.40,9696.30,2273.70,2977.60
2016-11-25,8114.30,21747.80,3639.05,4763.16,4587.85,6960.75,8692.59,1504.87,2080.60,7745.20,...,3208.65,11085.00,163.45,3668.85,9408.20,2707.05,3458.35,9806.45,2300.90,3016.25
2016-11-28,8126.90,21907.85,3660.85,4790.43,4620.77,6983.40,8732.74,1515.48,2098.40,7776.18,...,3126.95,11110.25,166.40,3719.70,9486.15,2748.00,3497.65,9890.10,2323.20,3050.50
2016-11-29,8142.15,21929.45,3689.45,4828.05,4652.51,7003.60,8855.83,1525.51,2096.00,7812.22,...,3114.05,11061.30,167.20,3717.00,9615.25,2759.25,3535.70,9915.05,2336.35,3049.15
2016-11-30,8224.50,22184.65,3750.10,4887.42,4714.26,7079.40,8943.86,1549.24,2113.50,7885.82,...,3179.50,11080.05,167.85,3743.60,9766.05,2791.95,3572.05,9938.95,2360.20,3079.15
2016-12-01,8192.90,21974.15,3699.45,4842.62,4681.38,7040.25,8817.67,1527.34,2099.40,7841.93,...,3140.90,11132.05,165.75,3695.25,9720.55,2767.40,3549.65,9876.35,2359.80,3047.45
2016-12-02,8086.80,21683.20,3634.50,4772.22,4621.10,6947.30,8643.82,1505.21,2072.70,7756.30,...,3114.00,11038.05,162.70,3655.75,9534.20,2737.80,3491.50,9804.50,2339.00,3024.80
2016-12-05,8128.75,21881.10,3666.35,4793.87,4622.97,6984.25,8679.08,1527.70,2081.90,7817.44,...,3147.40,11073.50,163.85,3667.10,9711.65,2748.45,3555.00,9808.00,2340.45,3042.60
2016-12-06,8143.15,21937.35,3691.50,4814.69,4649.55,7001.60,8724.96,1537.86,2085.35,7833.89,...,3161.30,11069.85,166.20,3688.75,9661.40,2759.25,3538.35,9901.70,2356.15,3071.80
2016-12-07,8102.05,21916.15,3675.00,4797.83,4622.74,6971.20,8716.64,1523.44,2078.95,7808.56,...,3110.35,10832.65,164.20,3709.25,9629.30,2752.40,3527.35,9912.95,2358.15,3074.35
2016-12-08,8246.85,22307.40,3743.10,4863.64,4679.24,7089.25,8867.93,1556.24,2117.90,7920.09,...,3153.35,10972.65,166.65,3759.50,9830.15,2782.90,3592.55,10066.90,2396.40,3132.65
2016-12-09,8261.75,22237.75,3784.45,4882.66,4705.57,7101.15,8895.10,1576.02,2120.75,7914.70,...,3230.55,10929.45,169.65,3761.10,9842.75,2780.00,3590.20,10111.95,2397.10,3135.45
2016-12-12,8170.80,21965.45,3723.00,4829.78,4666.16,7023.20,8740.37,1558.16,2097.55,7813.94,...,3180.95,10895.90,168.75,3739.75,9725.05,2770.95,3530.35,10060.50,2391.40,3101.75
2016-12-13,8221.80,21865.00,3726.25,4812.11,4673.34,7045.35,8650.24,1559.67,2106.45,7828.05,...,3200.40,10947.90,166.75,3748.75,9697.70,2783.25,3538.90,10149.95,2395.30,3093.95
2016-12-14,8182.45,21666.65,3703.50,4782.12,4634.75,7004.65,8584.83,1546.56,2085.95,7775.84,...,3158.80,10859.25,167.45,3685.55,9612.70,2757.45,3521.40,10154.15,2342.95,3062.40
2016-12-15,8153.60,21630.55,3724.60,4788.70,4648.16,6989.25,8591.01,1555.86,2085.90,7750.07,...,3182.60,10655.50,167.85,3677.70,9592.70,2748.95,3508.25,10114.90,2346.20,3049.30
2016-12-16,8139.45,21593.40,3708.55,4779.09,4636.23,6976.50,8542.51,1542.55,2077.20,7738.71,...,3169.05,10646.50,167.70,3649.25,9599.55,2736.05,3493.95,10080.65,2319.65,3018.95